name: Deploy to aws s3

on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Application _ deployment 
          path: dist
      - name: Deploy
        run: aws s3 sync . s3://jirabucketformyproject
      
          
